module.exports={
    apps:[
        {
            name:'bms-backend',
            script:'dist/server.js',
            instance:'max',
            exec_mode:'cluster',
            env:{
                NODE_ENV:'development'
            },
            env_production:{
                NODE_ENV:'production'
            }
        }
    ]
}